apiVersion: apps/v1
kind: Deployment
metadata:
  name: Real-app
spec:
  replicas: 9
  selector:
    matchLabels:
      app: checkout-apps
  template:
    metadata:
      labels:
        app: checkout-app
    spec:
      containers:
        - name: checkout-app
          image: myrepo/checkout-app:1.0.0
          ports:
            - KubernetesPort: 8082
