apiVersion: apps/v1
kind: Deployment
metadata:
  name: Generic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-app
  template:
    metadata:
      labels:
        app: checkout-app
    spec:
      containers:
        - name: checkout-app
          image: myrepo/checkout-app:1.0.0
          ports:
            - DockerPort: 8082
